//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.04 at 12:43:40 AM CEST 
//


package model.ir;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}banka_ir"/>
 *         &lt;element ref="{}duznik_ir"/>
 *         &lt;element ref="{}poverilac_ir"/>
 *         &lt;element ref="{}detalji_izvoda_racuna"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bankaIr",
    "duznikIr",
    "poverilacIr",
    "detaljiIzvodaRacuna"
})
@XmlRootElement(name = "izvod_racuna")
public class IzvodRacuna implements Serializable{

    @XmlElement(name = "banka_ir", required = true)
    protected BankaIr bankaIr;
    @XmlElement(name = "duznik_ir", required = true)
    protected DuznikIr duznikIr;
    @XmlElement(name = "poverilac_ir", required = true)
    protected PoverilacIr poverilacIr;
    @XmlElement(name = "detalji_izvoda_racuna", required = true)
    protected DetaljiIzvodaRacuna detaljiIzvodaRacuna;

    /**
     * Gets the value of the bankaIr property.
     * 
     * @return
     *     possible object is
     *     {@link BankaIr }
     *     
     */
    public BankaIr getBankaIr() {
        return bankaIr;
    }

    /**
     * Sets the value of the bankaIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankaIr }
     *     
     */
    public void setBankaIr(BankaIr value) {
        this.bankaIr = value;
    }

    /**
     * Gets the value of the duznikIr property.
     * 
     * @return
     *     possible object is
     *     {@link DuznikIr }
     *     
     */
    public DuznikIr getDuznikIr() {
        return duznikIr;
    }

    /**
     * Sets the value of the duznikIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DuznikIr }
     *     
     */
    public void setDuznikIr(DuznikIr value) {
        this.duznikIr = value;
    }

    /**
     * Gets the value of the poverilacIr property.
     * 
     * @return
     *     possible object is
     *     {@link PoverilacIr }
     *     
     */
    public PoverilacIr getPoverilacIr() {
        return poverilacIr;
    }

    /**
     * Sets the value of the poverilacIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoverilacIr }
     *     
     */
    public void setPoverilacIr(PoverilacIr value) {
        this.poverilacIr = value;
    }

    /**
     * Gets the value of the detaljiIzvodaRacuna property.
     * 
     * @return
     *     possible object is
     *     {@link DetaljiIzvodaRacuna }
     *     
     */
    public DetaljiIzvodaRacuna getDetaljiIzvodaRacuna() {
        return detaljiIzvodaRacuna;
    }

    /**
     * Sets the value of the detaljiIzvodaRacuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetaljiIzvodaRacuna }
     *     
     */
    public void setDetaljiIzvodaRacuna(DetaljiIzvodaRacuna value) {
        this.detaljiIzvodaRacuna = value;
    }

}
