//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 03:39:49 PM CEST 
//


package model.xmlws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="nalog_za_prenos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="podaci_o_duzniku" type="{http://www.ftn.uns.ac.rs/nalog}TFizicko_lice"/>
 *                   &lt;element name="podaci_o_poveriocu" type="{http://www.ftn.uns.ac.rs/nalog}TPravno_lice"/>
 *                   &lt;element name="svrha_placanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="podaci_o_uplati">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sifra_placanja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="valuta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="racun_primaoca" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="transfer_podaci">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="broj_modela" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="poziv_na_broj" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nalogZaPrenos"
})
@XmlRootElement(name = "nalozi")
public class Nalozi {

    @XmlElement(name = "nalog_za_prenos", required = true)
    protected List<Nalozi.NalogZaPrenos> nalogZaPrenos;

    /**
     * Gets the value of the nalogZaPrenos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nalogZaPrenos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNalogZaPrenos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nalozi.NalogZaPrenos }
     * 
     * 
     */
    public List<Nalozi.NalogZaPrenos> getNalogZaPrenos() {
        if (nalogZaPrenos == null) {
            nalogZaPrenos = new ArrayList<Nalozi.NalogZaPrenos>();
        }
        return this.nalogZaPrenos;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="podaci_o_duzniku" type="{http://www.ftn.uns.ac.rs/nalog}TFizicko_lice"/>
     *         &lt;element name="podaci_o_poveriocu" type="{http://www.ftn.uns.ac.rs/nalog}TPravno_lice"/>
     *         &lt;element name="svrha_placanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="podaci_o_uplati">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sifra_placanja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="valuta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="racun_primaoca" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="transfer_podaci">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="broj_modela" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="poziv_na_broj" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podaciODuzniku",
        "podaciOPoveriocu",
        "svrhaPlacanja",
        "podaciOUplati"
    })
    public static class NalogZaPrenos {

        @XmlElement(name = "podaci_o_duzniku", required = true)
        protected TFizickoLice podaciODuzniku;
        @XmlElement(name = "podaci_o_poveriocu", required = true)
        protected TPravnoLice podaciOPoveriocu;
        @XmlElement(name = "svrha_placanja", required = true)
        protected String svrhaPlacanja;
        @XmlElement(name = "podaci_o_uplati", required = true)
        protected Nalozi.NalogZaPrenos.PodaciOUplati podaciOUplati;

        /**
         * Gets the value of the podaciODuzniku property.
         * 
         * @return
         *     possible object is
         *     {@link TFizickoLice }
         *     
         */
        public TFizickoLice getPodaciODuzniku() {
            return podaciODuzniku;
        }

        /**
         * Sets the value of the podaciODuzniku property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFizickoLice }
         *     
         */
        public void setPodaciODuzniku(TFizickoLice value) {
            this.podaciODuzniku = value;
        }

        /**
         * Gets the value of the podaciOPoveriocu property.
         * 
         * @return
         *     possible object is
         *     {@link TPravnoLice }
         *     
         */
        public TPravnoLice getPodaciOPoveriocu() {
            return podaciOPoveriocu;
        }

        /**
         * Sets the value of the podaciOPoveriocu property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPravnoLice }
         *     
         */
        public void setPodaciOPoveriocu(TPravnoLice value) {
            this.podaciOPoveriocu = value;
        }

        /**
         * Gets the value of the svrhaPlacanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSvrhaPlacanja() {
            return svrhaPlacanja;
        }

        /**
         * Sets the value of the svrhaPlacanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSvrhaPlacanja(String value) {
            this.svrhaPlacanja = value;
        }

        /**
         * Gets the value of the podaciOUplati property.
         * 
         * @return
         *     possible object is
         *     {@link Nalozi.NalogZaPrenos.PodaciOUplati }
         *     
         */
        public Nalozi.NalogZaPrenos.PodaciOUplati getPodaciOUplati() {
            return podaciOUplati;
        }

        /**
         * Sets the value of the podaciOUplati property.
         * 
         * @param value
         *     allowed object is
         *     {@link Nalozi.NalogZaPrenos.PodaciOUplati }
         *     
         */
        public void setPodaciOUplati(Nalozi.NalogZaPrenos.PodaciOUplati value) {
            this.podaciOUplati = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sifra_placanja" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="valuta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="racun_primaoca" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="transfer_podaci">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="broj_modela" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="poziv_na_broj" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sifraPlacanja",
            "valuta",
            "iznos",
            "racunPrimaoca",
            "transferPodaci"
        })
        public static class PodaciOUplati {

            @XmlElement(name = "sifra_placanja", required = true)
            protected Object sifraPlacanja;
            @XmlElement(required = true)
            protected Object valuta;
            @XmlElement(required = true)
            protected Object iznos;
            @XmlElement(name = "racun_primaoca", required = true)
            protected Object racunPrimaoca;
            @XmlElement(name = "transfer_podaci", required = true)
            protected Nalozi.NalogZaPrenos.PodaciOUplati.TransferPodaci transferPodaci;

            /**
             * Gets the value of the sifraPlacanja property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getSifraPlacanja() {
                return sifraPlacanja;
            }

            /**
             * Sets the value of the sifraPlacanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setSifraPlacanja(Object value) {
                this.sifraPlacanja = value;
            }

            /**
             * Gets the value of the valuta property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getValuta() {
                return valuta;
            }

            /**
             * Sets the value of the valuta property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setValuta(Object value) {
                this.valuta = value;
            }

            /**
             * Gets the value of the iznos property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getIznos() {
                return iznos;
            }

            /**
             * Sets the value of the iznos property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setIznos(Object value) {
                this.iznos = value;
            }

            /**
             * Gets the value of the racunPrimaoca property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getRacunPrimaoca() {
                return racunPrimaoca;
            }

            /**
             * Sets the value of the racunPrimaoca property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setRacunPrimaoca(Object value) {
                this.racunPrimaoca = value;
            }

            /**
             * Gets the value of the transferPodaci property.
             * 
             * @return
             *     possible object is
             *     {@link Nalozi.NalogZaPrenos.PodaciOUplati.TransferPodaci }
             *     
             */
            public Nalozi.NalogZaPrenos.PodaciOUplati.TransferPodaci getTransferPodaci() {
                return transferPodaci;
            }

            /**
             * Sets the value of the transferPodaci property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nalozi.NalogZaPrenos.PodaciOUplati.TransferPodaci }
             *     
             */
            public void setTransferPodaci(Nalozi.NalogZaPrenos.PodaciOUplati.TransferPodaci value) {
                this.transferPodaci = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="broj_modela" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="poziv_na_broj" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "brojModela",
                "pozivNaBroj"
            })
            public static class TransferPodaci {

                @XmlElement(name = "broj_modela", required = true)
                protected Object brojModela;
                @XmlElement(name = "poziv_na_broj", required = true)
                protected Object pozivNaBroj;

                /**
                 * Gets the value of the brojModela property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getBrojModela() {
                    return brojModela;
                }

                /**
                 * Sets the value of the brojModela property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setBrojModela(Object value) {
                    this.brojModela = value;
                }

                /**
                 * Gets the value of the pozivNaBroj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getPozivNaBroj() {
                    return pozivNaBroj;
                }

                /**
                 * Sets the value of the pozivNaBroj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setPozivNaBroj(Object value) {
                    this.pozivNaBroj = value;
                }

            }

        }

    }

}
