//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 03:53:16 PM CEST 
//


package model.xmlws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.xmlws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.xmlws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nalozi }
     * 
     */
    public Nalozi createNalozi() {
        return new Nalozi();
    }

    /**
     * Create an instance of {@link Nalozi.NalogZaPrenos }
     * 
     */
    public Nalozi.NalogZaPrenos createNaloziNalogZaPrenos() {
        return new Nalozi.NalogZaPrenos();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link Nalozi.NalogZaPrenos.PodaciOPrenosu }
     * 
     */
    public Nalozi.NalogZaPrenos.PodaciOPrenosu createNaloziNalogZaPrenosPodaciOPrenosu() {
        return new Nalozi.NalogZaPrenos.PodaciOPrenosu();
    }

    /**
     * Create an instance of {@link Nalozi.NalogZaPrenos.TransferPodaciDuznik }
     * 
     */
    public Nalozi.NalogZaPrenos.TransferPodaciDuznik createNaloziNalogZaPrenosTransferPodaciDuznik() {
        return new Nalozi.NalogZaPrenos.TransferPodaciDuznik();
    }

    /**
     * Create an instance of {@link Nalozi.NalogZaPrenos.TransferPodaciPoverioc }
     * 
     */
    public Nalozi.NalogZaPrenos.TransferPodaciPoverioc createNaloziNalogZaPrenosTransferPodaciPoverioc() {
        return new Nalozi.NalogZaPrenos.TransferPodaciPoverioc();
    }

}
